mysql:
   image: mysql:5.7.10
   environment:
    MYSQL_DATABASE: cs4501
    MYSQL_USER: www
    MYSQL_PASSWORD: l33tp455w0rd
    DATABASE_PASSWORD: l33tp455w0rd
    MYSQL_ROOT_PASSWORD: r00tp455w0rd
   container_name: mysql

models:
   image: tp33/django-docker:1.3
   links:
     - mysql:db
   volumes:
     - ./models:/app
   ports:
     - "8000:8000"
   command: bash -c "python manage.py makemigrations accounts && python manage.py makemigrations ride && python manage.py migrate && python manage.py runmodwsgi --reload-on-changes"
   container_name: models

experience:
  build: ./experience/
  links:
    - models:models
    - kafka:kafka
    - es:es
  volumes:
    - ./experience:/code
  ports:
    - "8001:8000"
  command: python manage.py runmodwsgi --reload-on-changes
  container_name: experience

frontend:
   build: ./frontend/
   links:
     - experience:experience
   volumes:
     - ./frontend:/code
   ports:
     - "8002:8000"
   command: python manage.py runmodwsgi --reload-on-changes
   container_name: frontend

kafka:
   image: spotify/kafka
   mem_limit: 256m
   container_name: kafka
   environment:
     ADVERTISED_HOST: kafka
     ADVERTISED_PORT: 9092
   hostname: kafka

batch:
   build: ./batch/
   links:
     - es:es
     - kafka:kafka
   volumes:
     - ./batch:/code
   ports:
     - "8003:8000"
   command: python consume.py
   container_name: batch

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
       - "9200:9200"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
    