mysql:
   image: mysql:5.7.10
   environment:
    MYSQL_DATABASE: cs4501
    MYSQL_USER: www
    MYSQL_PASSWORD: l33tp455w0rd
    DATABASE_PASSWORD: l33tp455w0rd
    MYSQL_ROOT_PASSWORD: r00tp455w0rd
   container_name: mysql
models:
   image: tp33/django-docker:1.3
   links:
     - mysql:db
   volumes:
     - ./models:/app
   ports:
     - "8000:8000"
   command: bash -c "python manage.py makemigrations accounts && python manage.py makemigrations ride && python manage.py migrate && python manage.py runmodwsgi --reload-on-changes"
   container_name: models
experience:
   build: ./experience/
   links:
     - models:models
     - kafka:kafka
     - es:es
   volumes:
     - ./experience:/code
   ports:
     - "8001:8000"
   command: python manage.py runmodwsgi --reload-on-changes
   container_name: experience
frontend:
   build: ./frontend/
   links:
     - experience:experience
   volumes:
     - ./frontend:/code
   ports:
     - "8002:8000"
   command: python manage.py runmodwsgi --reload-on-changes
   container_name: frontend
kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
     ADVERTISED_HOST: kafka
     ADVERTISED_PORT: 9092
   hostname: kafka
   links:
     - batch:batch
batch:
   build: ./batch/
   links:
     - es:es
   volumes:
     - ./batch:/code
   ports:
     - "8003:8000"
   command: python consume.py
   container_name: batch
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
       - "9200:9200"
